# Stubs for com.jcraft.jsch package (JSch library)
# These are non-functional; they just define signatures for linting/autocomplete.

class JSch(object):
	def __init__(self): ...
	def getSession(self, username, host, port): ...
	def addIdentity(self, prvkey, pubkey=None, passphrase=None): ...
	def setKnownHosts(self, filename): ...


class Session(object):
	def connect(self, timeout=None): ...
	def disconnect(self): ...
	def isConnected(self): ...
	def openChannel(self, type): ...
	def setPassword(self, password): ...
	def setConfig(self, key, value): ...


class Channel(object):
	def connect(self, timeout=None): ...
	def disconnect(self): ...
	def isClosed(self): ...
	def getInputStream(self): ...
	def getOutputStream(self): ...
	def setInputStream(self, ins): ...
	def setOutputStream(self, out): ...
	def isConnected(self): ...


class ChannelExec(Channel):
	def setCommand(self, command): ...
	def setErrStream(self, out): ...
	def setInputStream(self, ins): ...
	def setOutputStream(self, out): ...


class ChannelSftp(Channel):
	def cd(self, path): ...
	def pwd(self): ...
	def ls(self, path): ...
	def get(self, src, dst=None, monitor=None): ...
	def put(self, src, dst=None, monitor=None): ...
	def rename(self, oldpath, newpath): ...
	def rm(self, path): ...
	def mkdir(self, path): ...
	def rmdir(self, path): ...
	def stat(self, path): ...
	def lstat(self, path): ...
	def exit(self): ...


class SftpATTRS(object):
	def getPermissions(self): ...
	def getSize(self): ...
	def isDir(self): ...
	def isLink(self): ...
	def getMTime(self): ...
	def getATime(self): ...


class SftpException(Exception):
	def __init__(self, id, message): ...


class UserInfo(object):
	def getPassphrase(self): ...
	def getPassword(self): ...
	def promptPassword(self, message): ...
	def promptPassphrase(self, message): ...
	def promptYesNo(self, message): ...
	def showMessage(self, message): ...